version: 2.0

references:
  # Environment variables
  #
  WP_CORE_DIR: &WP_CORE_DIR
    /tmp/wordpress
  WP_HOST: &WP_HOST
    passwords-evolved.test
  WP_ORG_PLUGIN_NAME: &WP_ORG_PLUGIN_NAME
    passwords-evolved
  WP_ORG_USERNAME: &WP_ORG_USERNAME
    carlalexander

  # Default container configuration
  #
  container_config: &container_config
    docker:
      - image: circleci/php:7.2
    environment:
      - WP_CORE_DIR: *WP_CORE_DIR
      - WP_HOST: *WP_HOST
      - WP_ORG_PLUGIN_NAME: *WP_ORG_PLUGIN_NAME
      - WP_ORG_USERNAME: *WP_ORG_USERNAME
    working_directory: ~/passwords-evolved

  workspace_root: &workspace_root
    /tmp

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  copy_vendor: &copy_vendor
    run:
      name: Copy vendor directory
      command: cp -R /tmp/vendor .

  install_subversion: &install_subversion
    run:
      name: Install subversion
      command: sudo apt-get install subversion

jobs:
  deploy_assets:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *install_subversion
      - run:
          name: Deploy assets to WordPress plugin directory
          command: .circleci/deploy-assets.sh

  deploy_plugin:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *install_subversion
      - run:
          name: Deploy new version to WordPress plugin directory
          command: .circleci/deploy-plugin.sh

workflows:
  version: 2
  deploy:
    jobs:
      - deploy_assets:
          filters:
            branches:
              only:
                - master
      # - deploy_plugin:
      #     filters:
      #       branches:
      #         only:
      #           - master